services:
  server:
    build: .
    working_dir: /usr/src/app
    ports:
      - "8000:5000"
    volumes:
      - .:/usr/src/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:5000"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: runServer.sh
